GET http://localhost:5000/posts/

###
POST http://localhost:5000/posts/create
Content-Type: application/json

{
  "title": "Hello world",
  "time_read": 4,
  "desc": "test",
  "img": "chrome://new-tab-page/icons/google_logo.svg",
  "author": "CoderX",
  "content": "Test content",
  "genre": "IT"
}

###
PUT http://localhost:5000/posts/update
Content-Type: application/json

{
  "_id": "60f26cd93eaa2e5cda295fd1",
  "title": "update",
  "time_read": 4,
  "desc": "test",
  "img": "chrome://new-tab-page/icons/google_logo.svg",
  "author": "CoderX",
  "content": "Test content",
  "genre": "IT"
}

###
DELETE http://localhost:5000/posts/delete
Content-Type: application/json

{
  "_id": "60f26cfb3eaa2e5cda295fd5"
}

###
POST http://localhost:5000/user/sign-up
Content-Type: application/json

{
  "username": "DuyetVu",
  "password": "123"
}

###
POST http://localhost:5000/user/sign-in
Content-Type: application/json

{
  "username": "DuyetVu",
  "password": "123"
}

###
POST http://localhost:5000/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjU4MjQzNzEsImV4cCI6MTYyNTgyNDQwMX0.BzKAzZOAaOQ3ZM9UQKIX8ZjKHYp7SMIHBv-Vdsdu98w

###
POST http://localhost:5000/user/refresh-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGU3ZDdjZWI1N2VkNDQ0NWMwYWU5MTciLCJpYXQiOjE2MjU4MjQzMzJ9.zVjfKzc2kyURjNmrjoMT81a64XgGibqnpS48Apu7RmE"
}

###
POST http://localhost:5000/user/log-out
Content-Type: application/json
